names = [
    "Updated by thread 1",
    "Updated by thread 0",
    "Updated by thread 2",
    "Updated by thread 3",
    "Updated by thread 0",
    "Updated by thread 1",
    "Updated by thread 3",
    "Updated by thread 2",
    "Updated by thread 1",
    "Updated by thread 2",
    "Updated by thread 3",
    "Updated by thread 0",
    "Updated by thread 0",
    "Updated by thread 1",
    "Updated by thread 2",
    "Updated by thread 3",
    "Updated by thread 0",
    "Updated by thread 1",
    "Updated by thread 2",
    "Updated by thread 3",
    "Updated by thread 0",
    "Updated by thread 1",
    "Updated by thread 2",
    "Updated by thread 3",
]
count = 24
enabled = false
